#!/bin/bash
# GCE setup script for bioinformatics
# Using Ubuntu 16.04 LTS as a starting point

# Update system
apt-get update

# Install Anaconda
cd /tmp
curl -O https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
sha256sum Anaconda3-5.0.1-Linux-x86_64.sh
bash Anaconda3-5.0.1-Linux-x86_64.sh
source ~/.bashrc

# Create environment in Conda and activate it
conda create --name BioSandbox python=3.6
source activate BioSandbox

# Setup channels for conda-package manager to use bioconda
conda config --add channels r
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda

# Install Conda-packages for bioinformatics
conda install fastqc # Install FastQC - Quality Control of Reads
sudo apt-get install ttf-dejavu # Get fonts for FastQC

## Assemblers
conda install spades # Install SPAdes assembler

## Aligners
conda install bwa # Install Burrows-Wheeler Aligner
conda install mummer # Install MUMmer - for rapid alignment of entire genomes

## Annotation
conda install prokka # Install prokka - annotation of prokaryote genomes
